<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="BookUI.aspx.cs" Inherits="SE0715_Group1_Lab4.GUI.BookUI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        &nbsp;</p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>List of books</b></p>
    <p>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Book number:&nbsp;&nbsp;
        <asp:TextBox ID="tbBookNum" runat="server"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btFilter" runat="server" Text="Filter" 
            onclick="btFilter_Click" />
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The number of books:
        <asp:Label ID="lbNum" runat="server" Text="Label"></asp:Label>
    </p>
    <p>
        <asp:GridView ID="gvBook" runat="server" AllowPaging="True" AllowSorting="True" 
            AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" 
            onpageindexchanging="gvBook_PageIndexChanging" 
            onrowdeleting="gvBook_RowDeleting" onsorting="gvBook_Sorting">
            <PagerSettings FirstPageText="" LastPageText="" PageButtonCount="5" />
            <SelectedRowStyle BackColor="Yellow" />
        </asp:GridView>
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btAdd" runat="server" onclick="btAdd_Click" Text="Add" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btEdit" runat="server" onclick="btEdit_Click" 
            style="height: 26px" Text="Edit" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btCopies" runat="server" onclick="btCopies_Click" 
            style="height: 26px" Text="Copies" />
    </p>
</asp:Content>
