<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CopyBookUI.aspx.cs" Inherits="SE0715_Group1_Lab4.GUI.CopyBookUI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        &nbsp;</p>
    <p>
        &nbsp;<b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; List of copies</b></p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Book number:&nbsp;&nbsp;
        <asp:TextBox ID="tbBookNum" runat="server"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tittle:&nbsp;&nbsp;
        <asp:TextBox ID="tbTittle" runat="server"></asp:TextBox>
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The number of copies:&nbsp;&nbsp;
        <asp:Label ID="lbNum" runat="server" Text="Label"></asp:Label>
    </p>
    <p>
        <asp:GridView ID="gvCopyBook" runat="server" AllowPaging="True" 
            AllowSorting="True" AutoGenerateDeleteButton="True" 
            AutoGenerateSelectButton="True" 
            onpageindexchanging="gvCopyBook_PageIndexChanging" 
            onrowdeleting="gvCopyBook_RowDeleting" onsorting="gvCopyBook_Sorting">
            <SelectedRowStyle BackColor="Yellow" />
        </asp:GridView>
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btAdd" runat="server" onclick="btAdd_Click" Text="Add" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btEdit" runat="server" onclick="btEdit_Click" Text="Edit" />
    </p>
</asp:Content>
