<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MemberUI.aspx.cs" Inherits="SE0715_Group1_Lab4.GUI.MemberUI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        &nbsp;</p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>List of members</b></p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The number of members:
        <asp:Label ID="lbNum" runat="server" Text="Label"></asp:Label>
    </p>
    <p>
        <asp:GridView ID="gvMember" runat="server" AllowPaging="True" 
            AllowSorting="True" AutoGenerateDeleteButton="True" 
            AutoGenerateSelectButton="True" onpageindexchanging="gvBook_PageIndexChanging" 
            onrowdeleting="gvBook_RowDeleting" onsorting="gvBook_Sorting">
            <PagerSettings FirstPageText="" LastPageText="" PageButtonCount="5" />
            <SelectedRowStyle BackColor="Yellow" />
        </asp:GridView>
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btAdd" runat="server" onclick="btAdd_Click" Text="Add" />
&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btEdit" runat="server" onclick="btEdit_Click" 
            style="height: 26px" Text="Edit" />
&nbsp;&nbsp;&nbsp;&nbsp;
    </p>
</asp:Content>
